CREATE TABLE TBL_BOOKS(
book_id INT PRIMARY KEY  NOT NULL,
author VARCHAR2(50) NOT NULL,
title VARCHAR(50) NOT NULL,
rating FLOAT NOT NULL
);

DROP TABLE TBL_BOOKS;
DROP TABLE TBL_USERS;

CREATE TABLE TBL_USERS(
user_id INT PRIMARY KEY NOT NULL,
username VARCHAR2(20) NOT NULL,
u_password VARCHAR2(50) NOT NULL,
u_role VARCHAR2(20) NOT NULL,
is_enabled BOOLEAN NOT NULL
);

-----TABLE FOR h2 DB  DO NTO CREATE FOR NOW
CREATE TABLE TBL_USERS(
id INT PRIMARY KEY NOT NULL,
username VARCHAR2(20) NOT NULL,
password VARCHAR2(50) NOT NULL,
role VARCHAR2(20) NOT NULL
);

DROP TABLE TLB_USERS;
SELECT* FROM TBL_USERS;




SELECT * FROM TBL_USER;

CREATE TABLE TBL_LIBRARY(
--library_id INT PRIMARY KEY NOT NULL,
user_id INT NOT NULL,
book_id INT NOT NULL,
FOREIGN KEY (book_id) REFERENCES BOOK(book_id) ON DELETE CASCADE,
FOREIGN KEY (user_id) REFERENCES TBL_USER(user_id) ON DELETE CASCADE
);

INSERT INTO TBL_USER VALUES(2,'svetlyo','password','AUTHOR');
INSERT INTO BOOK VALUES(1,'svetlyo','sve',4.5);
INSERT INTO BOOK VALUES(2,'Kalin','Ka',6);
INSERT INTO TBL_LIBRARY VALUES(1,1);
INSERT INTO TBL_LIBRARY VALUES(2,1);



SELECT * FROM BOOK;

SELECT * FROM TBL_LIBRARY;

DROP TABLE TBL_LIBRARY;


SELECT * FROM TBL_USER;

commit;
